//
//  WeaponData.h
//  BEUEngine
//
//  Created by Chris Mele on 7/25/10.
//  Copyright 2010 Invulse. All rights reserved.
//



#define PENGUIN_WEAPON_EMPTY -1
#define PENGUIN_WEAPON_NONE 0
#define PENGUIN_WEAPON_KATANA 1
#define PENGUIN_WEAPON_BIGSWORD 2
#define PENGUIN_WEAPON_SHORTSWORD 3
#define PENGUIN_WEAPON_SCIMITAR 4
#define PENGUIN_WEAPON_SWORDFISH 5
#define PENGUIN_WEAPON_LASERSWORD 6
#define PENGUIN_WEAPON_AXE 7

#define PENGUIN_WEAPON_PISTOL 8

#define PENGUIN_WEAPON_BASEBALLBAT 9
#define PENGUIN_WEAPON_SABER 10

#define PENGUIN_WEAPON_SHURIKEN 11

#define PENGUIN_WEAPON_MEATCLEAVER 12
#define PENGUIN_WEAPON_SLEDGEHAMMER 13
#define PENGUIN_WEAPON_MACHETE 14

#define PENGUIN_WEAPON_CHAINSAW 15
#define PENGUIN_WEAPON_PIPEWRENCH 16
#define PENGUIN_WEAPON_DIVINEBLADE 17


#define PENGUIN_WEAPON_TYPE_NONE 0
#define PENGUIN_WEAPON_TYPE_SWINGABLE 1
#define PENGUIN_WEAPON_TYPE_PISTOL 2
#define PENGUIN_WEAPON_TYPE_THROWABLE 3
#define PENGUIN_WEAPON_TYPE_HEAVY 4

#define NUM_WEAPON_SLOTS 3